version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    # runtime: nvidia
    ports:
      - "8501:8501"
    volumes:
      - .:/app  # Map the current directory to the /app directory in the container
    environment:
      - HF_HOME=/models
      - MODEL=diffusers/stable-diffusion-xl-1.0-inpainting-0.1
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    container_name: stable_diffusion_app
    entrypoint: ["/app/entrypoint.sh"]
